[package]
name = "candle-rotary"
version = "0.0.1"
edition = "2021"

description = "Rotary layer for the candle ML framework."
keywords = ["tensor", "machine-learning"]
categories = ["science"]
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
#candle = { version = "*", package = "candle-core", features = ["cuda"]}
candle = { git = "https://github.com/spiceai/candle.git", version = "0.8", rev = "a84593f1951a4a9083e29257003a8112eb1450da", package = "candle-core", default-features = false }
half = { version = "2.3.1", features = ["num-traits"] }

[build-dependencies]
anyhow = { version = "1", features = ["backtrace"] }
bindgen_cuda = "0.1.1"

[dev-dependencies]
anyhow = { version = "1", features = ["backtrace"] }
candle-nn = { version = "0.3.0", features = ["cuda"] }

[features]
dynamic-linking = []